blank_issues_enabled: false
contact_links:
  - name: ğŸ“šDocumentation
    url: http://docs.guzzlephp.org
    about: Check the documentation before opening an issue.

  - name: â“Support
    url: https://git.io/guzzle-support
    about: We use GitHub issues only to discuss bugs and new features.
